=== FP4-is-All-you-Need/AWE/schema/index.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:awe:schema:index:1",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "data_version",
    "complete",
    "count",
    "files"
  ],
  "properties": {
    "schema_version": {
      "const": 1
    },
    "data_version": {
      "type": "string",
      "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
    },
    "complete": {
      "type": "boolean"
    },
    "count": {
      "type": "integer",
      "minimum": 0
    },
    "files": {
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "path",
          "count",
          "sha256"
        ],
        "properties": {
          "path": {
            "type": "string",
            "pattern": "^solutions/[0-9a-f]{2}\\.json$"
          },
          "count": {
            "type": "integer",
            "minimum": 1
          },
          "sha256": {
            "type": "string",
            "pattern": "^[0-9a-f]{64}$"
          }
        }
      }
    },
    "search": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "sha256"
      ],
      "properties": {
        "path": {
          "const": "search/index.json"
        },
        "sha256": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        }
      }
    },
    "modular": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "sha256"
      ],
      "properties": {
        "path": {
          "const": "modular/index.json"
        },
        "sha256": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        }
      }
    },
    "input_inventory": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "sha256"
      ],
      "properties": {
        "path": {
          "const": "input-inventory.json"
        },
        "sha256": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        }
      }
    }
  }
}

=== FP4-is-All-you-Need/AWE/index.json
{"complete":true,"count":184629,"data_version":"0.1.0","files":[{"count":724,"path":"solutions/00.json","sha256":"51d2fe3be74a14644689cb36e36a5e16fe556b1bae36d1016697ec5561d23215"},{"count":703,"path":"solutions/01.json","sha256":"08cf3674e9af04af3e0718934533c74f399e2cde90f678542e572ad6380cfcd7"},{"count":713,"path":"solutions/02.json","sha256":"92cae4bd2e79915d54dcde90454678cb34d111243f6b838e72ef0e05dcde2cb2"},{"count":734,"path":"solutions/03.json","sha256":"2318722dc4b0a26f6c7a77008d48e925f236ac9c6bc0fca93c6cb15e93604d59"},{"count":709,"path":"solutions/04.json","sha256":"40f81dac12d6488a73fd6c64729b08f9d390034b902a3d65a58c3c141f575cf8"},{"count":679,"path":"solutions/05.json","sha256":"6a8389065f6b127a06363172210e3aa4e5edc7c5775f5dd043c7553d8378f740"},{"count":719,"path":"solutions/06.json","sha256":"f4bedc44279d982ed5e286150018160e12b14d95afd730669bcb4cc075970a8e"},{"count":728,"path":"solutions/07.json","sha256":"21e784b8ed35b428abb34f56377cd8725056f5a4b7391d146771529bbe803462"},{"count":718,"path":"solutions/08.json","sha256":"4915b0543353cda1203dcc893d261b22bb3cf4fd750a2700fbd3368508222a7b"},{"count":709,"path":"solutions/09.json","sha256":"ff08a960046035645017e3be77d835234eae8de32c3e5d1fb6036ba26a1341d4"},{"count":732,"path":"solutions/0a.json","sha256":"f30482001c4383b34bc53b2ad0390c1b654b204db20a4a7a1f5f0cfcd83790fb"},{"count":750,"path":"solutions/0b.json","sha256":"fa1fc3e796e71b268dadf48f6ad4b77abb954b9d04345054fbc4619b6e532be2"},{"count":720,"path":"solutions/0c.json","sha256":"91783a631745532cb2743fdc71d32f007a9bd57d6b51e8eddc9813cd20405347"},{"count":742,"path":"solutions/0d.json","sha256":"6e65a3cfa959d8d7a078a87d80b7c0118b7e6109114c317b1cd4eaba7d4e6b1a"},{"count":716,"path":"solutions/0e.json","sha256":"32d18e4f6998225227bf97628426165ad42cc6c53b0fec3384cf1d5cfebdc538"},{"count":713,"path":"solutions/0f.json","sha256":"83188f6cd212b1bd2407a958e2bbca3a89a812972ff307e5bbde5b4cfc4c3d3b"},{"count":723,"path":"solutions/10.json","sha256":"55fe02945efcd7575f960525dd53ba561d36a99cfd2e1058b7ac79ec9c280fe2"},{"count":742,"path":"solutions/11.json","sha256":"bd28ef23136c2b8e493b67ce37f4e4aa8bc6e03ff9650cd2a24da59819cf8fd0"},{"count":697,"path":"solutions/12.json","sha256":"2eca805c5d4d1938c23054724a01b5a7945d30c8e380c8a283a71184c9ddf78a"},{"count":699,"path":"solutions/13.json","sha256":"3b5e355e4ae292331d70e5d8aa554b962ed80b1ceb1e2202fd27f9f6911a66c6"},{"count":730,"path":"solutions/14.json","sha256":"5d3c49d9a35e6e438cfeb4f47d064eeb02fb80afda43f6a5c485c72720952a08"},{"count":675,"path":"solutions/15.json","sha256":"0a0699b9e7bfb62fa6bc9c49f3d50e10c770e55681d98d2509fca618f6f065a3"},{"count":735,"path":"solutions/16.json","sha256":"b4e0a4d768504291981533ab354fd3d081b50a1459d6c870f1a63de75c5078eb"},{"count":758,"path":"solutions/17.json","sha256":"72ec70aac35f79701637f67402d446edd532ee71fddd14a3407d34852945ae81"},{"count":722,"path":"solutions/18.json","sha256":"bacd6ef0588ea1dbf254f1fdc2ba38dc421bec936a5643dccd978fed07ea7b99"},{"count":735,"path":"solutions/19.json","sha256":"1fab08184ba33ecceda108b68a756c62e06b8abf3ab187062e05f45dc25d44b7"},{"count":699,"path":"solutions/1a.json","sha256":"b8e8af471107ce72f3202fc0d6653d54656552602a5052a02588aba84b007596"},{"count":715,"path":"solutions/1b.json","sha256":"351f2b45657e247ee1a2f3d9a28efeedeb5e8222b4b8c1e7e7cc6ff85b983182"},{"count":686,"path":"solutions/1c.json","sha256":"cc386bfa74d59551419e1866f77d2f9425d633a987006991f9685e7f5ece4f81"},{"count":699,"path":"solutions/1d.json","sha256":"ad95d4d1251a0bd4970b190c923dd9e244d563b9784217dfaacaa0a9c815f9b9"},{"count":676,"path":"solutions/1e.json","sha256":"d86ee4569e020f4cd3ca73c4f2986c502671dcae8c026334c582eee60aabaac4"},{"count":740,"path":"solutions/1f.json","sha256":"49a8d89f419d1c1ae60d2019c7baf55298db1d3fa77196539962cf2e3aadef7f"},{"count":717,"path":"solutions/20.json","sha256":"3296d4a04f290c21a57c3f30b937ed2911a168edc101a7bfa9cb7da6ac02f023"},{"count":720,"path":"solutions/21.json","sha256":"f257e393234a829a2214bf84ac409eede3565f6997c1e1485bed50e80aa40afb"},{"count":723,"path":"solutions/22.json","sha256":"d25ed2a7e7c5bbbf561781972fa14c0e68784e052b0c20daa1080f063e07d0cb"},{"count":691,"path":"solutions/23.json","sha256":"4539febb44ef0e97c36ee16e5b5b253f6427168a6d93b7f8031f488a039106ac"},{"count":752,"path":"solutions/24.json","sha256":"3c36d7cec7feb3ae4f16b780606bdc4d0ad0c496b903f71d200fd7229561f045"},{"count":726,"path":"solutions/25.json","sha256":"9c8fb86b753fc8d91ab1fb7300791d99ee438311d886c07bbd0f1b688429bec3"},{"count":727,"path":"solutions/26.json","sha256":"1302f30fd84c03e81bd9971f966d59743b4700f708d7dc9ed2995b15513b2468"},{"count":706,"path":"solutions/27.json","sha256":"75f6fb624815aea381227cf2b1a6d852b09a30a283debec6b849a122800b9c5f"},{"count":723,"path":"solutions/28.json","sha256":"3804d932d9a58eee9a94f7a2128ff67ef1ed158d3c18b100a8b2faba7ea810b3"},{"count":726,"path":"solutions/29.json","sha256":"120147c8e92b6db786e35ae1d3e57cc08df531d2f123e5b7c4741f99f895e043"},{"count":709,"path":"solutions/2a.json","sha256":"6cbacb1afa386d3397776bc344ec246e63bd0a4cf015a025a2d7a91bc93ec739"},{"count":696,"path":"solutions/2b.json","sha256":"3571eb5a85cc15957b0b8a83c720494a6f4f7927b57ff34e5763978d02fbff9c"},{"count":707,"path":"solutions/2c.json","sha256":"e7092a22126aa5b33cb625b075e233906aea8cc945be8a3ab41998a50dec9d33"},{"count":722,"path":"solutions/2d.json","sha256":"64ad9f966b907097fb0cc50f4d646e2beea320a220f9404dc2d8fe77a7639829"},{"count":707,"path":"solutions/2e.json","sha256":"698037ed6da35b10970917fa77ad9d501329b0cf123c7c57889322c9ba183f41"},{"count":725,"path":"solutions/2f.json","sha256":"9f50f363b53172eb10a671442e6b38d2949701efced5775e97e96c064c500f59"},{"count":735,"path":"solutions/30.json","sha256":"a5b4910dccfbb892744b36ad5084e63b191591893a4459b8ebe17bec28b8c32f"},{"count":731,"path":"solutions/31.json","sha256":"0fed520fc278e6adce9446283098df9107753c708bfa7050eefdeff4b109de50"},{"count":713,"path":"solutions/32.json","sha256":"e205fc3bf6df8127283bc27ca4e3743777fd46fac305a35e7cf5b74448b7f4d3"},{"count":707,"path":"solutions/33.json","sha256":"76d0d6be800c2f3d65cea5d1e7741dbc2c77093d024f2622598f52e63a40e850"},{"count":759,"path":"solutions/34.json","sha256":"74ea1fa8152575e04e7acc66e6267b3e275c345e26c29d49a7007c00dd72b743"},{"count":720,"path":"solutions/35.json","sha256":"b4af6253016a241312ac17f0a555dbb5b54c6ca20247756ca482fefaea053786"},{"count":728,"path":"solutions/36.json","sha256":"800b2e440b8c8bff01c48a540c3e41093c40294d075a304a9763c121cae6049f"},{"count":739,"path":"solutions/37.json","sha256":"9aefc989382cd7465eda8f3460d7bb49be6fd97d4635d436913e4870d6587c08"},{"count":662,"path":"solutions/38.json","sha256":"26b0688cf5c5b046af6fdbed9a6b928446a59aed9f304f3c9b63856020933209"},{"count":747,"path":"solutions/39.json","sha256":"e0d837c649c06326538807bf9813824dd540e41b064810080dc50f6652d921fa"},{"count":694,"path":"solutions/3a.json","sha256":"83555f8e08f44c6ecdf56305a40c9b4837def11a9677aece86a21d401bd7067f"},{"count":708,"path":"solutions/3b.json","sha256":"1f67af769e7620ffdc8d92674942e1ee3a9d6442b78c9a24e12a2e20bbd08c6e"},{"count":742,"path":"solutions/3c.json","sha256":"9ca2ca4f94db1d30029776e97ea7ee2530e113735c6e0cc3cf666064db850f12"},{"count":735,"path":"solutions/3d.json","sha256":"13215950d676c6b9a6ba36842f8fb22e9369b9eca81037a0feffc3d967321d93"},{"count":751,"path":"solutions/3e.json","sha256":"0a3982028dae7b93324d624461f59987a056daca51cf1b6f7792f72421392071"},{"count":723,"path":"solutions/3f.json","sha256":"183b815cc856a265b128b5718c72d397f8f40ab015afbc5b6c64857118f42042"},{"count":766,"path":"solutions/40.json","sha256":"47d25dce4e383463645a5845970749fc6a9614ca999815bf0127c8859b38df42"},{"count":720,"path":"solutions/41.json","sha256":"46377517fae1c815b0403ef33d08d0630b742b7f4f87a24290274cde308ec596"},{"count":705,"path":"solutions/42.json","sha256":"0a925ba528f6616b98b9809ae4504b98fa9114e9c2bb00d53471f7158a34f61a"},{"count":698,"path":"solutions/43.json","sha256":"4a0c97dcb832a3686c135955e696394c96f2f0f4239694e2ae8c42a2f8321922"},{"count":738,"path":"solutions/44.json","sha256":"69930ff1205fcc0943e5c009bf79af459e1752639d722df9f8150e44a0b568d0"},{"count":793,"path":"solutions/45.json","sha256":"6dafd9eb77d80b56802519ba04da38922601dfa7da0c0a75208fc7da785a221b"},{"count":708,"path":"solutions/46.json","sha256":"d39fd39fb3a5830a4be3d9d1b82de6254d93c33c52d55a3f1b807ebc86e0fed5"},{"count":700,"path":"solutions/47.json","sha256":"ea520b47292a5c6b480cc4624bda99b99de8624967c5cddfc3c4a105e8b594ca"},{"count":689,"path":"solutions/48.json","sha256":"65463ab24811346df2aef1801fa61030399750f8fc21961ad6b10e3b01ddf7fd"},{"count":766,"path":"solutions/49.json","sha256":"6774634311f864bc86550ae02a121bc98b4d0d399addac3dd9e39051987f8a5b"},{"count":689,"path":"solutions/4a.json","sha256":"7b32b4db559646f5fb9ab75d2d2a9b814599e9df02b436e5f4c1ab42365ca0f6"},{"count":727,"path":"solutions/4b.json","sha256":"2a0885370a7c52b79c39c25965db90bfb523564c97ef7db3ab65a13fb1a11392"},{"count":742,"path":"solutions/4c.json","sha256":"53c1d7caabaed2812dcea7aed73f035f53394ec91eeb92b7da7d23520b2a0aba"},{"count":674,"path":"solutions/4d.json","sha256":"631bf6a70f74a2e16c5f9b1196fb4276d10e7ba349687c35710c96650c4bad61"},{"count":712,"path":"solutions/4e.json","sha256":"53f6f412d6c0ab63c2ffd473cf5a327772f462a5ef84e97767f7a5025a3fac88"},{"count":700,"path":"solutions/4f.json","sha256":"396f7581036b1880f47c26bda14e1d1d99496fe7c6f05e9c5cdd18c3182d5087"},{"count":729,"path":"solutions/50.json","sha256":"2b50c3da79ffd7ec461b808249a4912ae3c8fd23732d7e5b7bd123a701a20851"},{"count":704,"path":"solutions/51.json","sha256":"cd63e454095d238f1b9173eea91860a074e484e1f4bb232837434aebb92c2f24"},{"count":732,"path":"solutions/52.json","sha256":"9dd8612417157c1969731e481bdf9b5feec01409fa23c6dade37d1d4a3e49adf"},{"count":719,"path":"solutions/53.json","sha256":"590995abb99d8d42073a7e76c1ae0b657f3f5cebffd60ca2f596dd9d9f58ae13"},{"count":718,"path":"solutions/54.json","sha256":"ed7ee0b8c8d44064a75552c7a0a334ceb6e5c6136bb479780f14f93e37
